-- ==============================================================================
-- BOUTIQUE HAMMAM NILE — AJOUT BOUTIQUE FEMME (125) ET BOUTIQUE HOMME (50)
-- A coller dans Supabase > SQL Editor, puis "Run".
-- Sans danger : n'insère que ces 175 nouveaux articles, ne touche à rien
-- d'existant (ON CONFLICT DO NOTHING = si un produit avec cet id existe
-- déjà, la ligne est ignorée au lieu d'écraser vos données).
-- ==============================================================================

INSERT INTO public.products (id, name, category, price, qty, "minQty", emoji)
VALUES
  (13, 'Jaclin (jedora)', 'femmes', 0, 0, 5, '💄'),
  (14, 'Neseem (burham)', 'femmes', 0, 0, 5, '💄'),
  (15, 'Tulipān negro (fresa & nata)', 'femmes', 0, 0, 5, '💄'),
  (16, 'Tulipān negro (candy fantasy)', 'femmes', 0, 0, 5, '💄'),
  (17, 'Tulipān negro (body mist)', 'femmes', 0, 0, 5, '🌸'),
  (18, 'Tulipān negro (coco pure white)', 'femmes', 0, 0, 5, '💄'),
  (19, 'Melano (exotic beach)', 'femmes', 0, 0, 5, '💄'),
  (20, 'Melano (pear gloss)', 'femmes', 0, 0, 5, '💄'),
  (21, 'Bien etre (eau de Cologne)', 'femmes', 0, 0, 5, '🌸'),
  (22, 'Saphir (select blue)', 'femmes', 0, 0, 5, '💄'),
  (23, 'Venus (déodorant océan)', 'femmes', 0, 0, 5, '🧴'),
  (24, 'Olive oil (huile)', 'femmes', 0, 0, 5, '🫙'),
  (25, 'Sensitélial (gel nettoyant)', 'femmes', 0, 0, 5, '💧'),
  (26, 'Romance (eau de parfum)', 'femmes', 0, 0, 5, '🌸'),
  (27, 'Elixir de miel (sérum réparateur)', 'femmes', 0, 0, 5, '💧'),
  (28, 'Venus (sun flower)', 'femmes', 0, 0, 5, '💄'),
  (29, 'Nivea mousse (eau hydratante)', 'femmes', 0, 0, 5, '💄'),
  (30, 'Nexton baby (spray moustique)', 'femmes', 0, 0, 5, '💄'),
  (31, 'Sébionex (gel nettoyant)', 'femmes', 0, 0, 5, '💧'),
  (32, 'Johnsons (huile baby)', 'femmes', 0, 0, 5, '🫙'),
  (33, 'Le ptt marseiliais (sublimante)', 'femmes', 0, 0, 5, '💄'),
  (34, 'Selon pro vitamine E (hair food)', 'femmes', 0, 0, 5, '💄'),
  (35, 'Vaseline (cocoa radiant body oil)', 'femmes', 0, 0, 5, '🫙'),
  (36, 'Desert flower (shampoo)', 'femmes', 0, 0, 5, '🧴'),
  (37, 'Lana inceller (huile termini...)', 'femmes', 0, 0, 5, '🫙'),
  (38, 'Nike woman (parfum)', 'femmes', 0, 0, 5, '🌸'),
  (39, 'L''Oréal paris elseve (parfum)', 'femmes', 0, 0, 5, '🌸'),
  (40, 'L''Oréal paris elseve (sérum hydratante)', 'femmes', 0, 0, 5, '💧'),
  (41, 'Venus new (mousse de douche)', 'femmes', 0, 0, 5, '💄'),
  (42, 'Calliderme (gel intime)', 'femmes', 0, 0, 5, '💧'),
  (43, 'Nuevo novo (huile coco et aleovera)', 'femmes', 0, 0, 5, '🫙'),
  (44, 'Nivea (lait de corps)', 'femmes', 0, 0, 5, '🧴'),
  (45, 'Nuevo novo (elixir de juventud)', 'femmes', 0, 0, 5, '💄'),
  (46, 'Rose Berry elastic & transculent (huile)', 'femmes', 0, 0, 5, '🫙'),
  (47, 'L''Oréal elseve sérum (huile extraordinaire coco)', 'femmes', 0, 0, 5, '🫙'),
  (48, 'Dove intensiva (crema nutriente)', 'femmes', 0, 0, 5, '🧴'),
  (49, 'Cosmolive (pink champagne)', 'femmes', 0, 0, 5, '💄'),
  (50, 'Cosmolive (hair perfectore)', 'femmes', 0, 0, 5, '💄'),
  (51, 'Dexeryl (crème)', 'femmes', 0, 0, 5, '🧴'),
  (52, 'Johnsons baby (champoo)', 'femmes', 0, 0, 5, '🧴'),
  (53, 'Licorice root (face wash)', 'femmes', 0, 0, 5, '💄'),
  (54, 'Palette intensive (crème color)', 'femmes', 0, 0, 5, '🧴'),
  (55, 'Mixa éclait (lait de corps)', 'femmes', 0, 0, 5, '🧴'),
  (56, 'SHaumar (pot vaselina neutra)', 'femmes', 0, 0, 5, '💄'),
  (57, 'L''Oréal paris (excellence creme)', 'femmes', 0, 0, 5, '🧴'),
  (58, 'ZARA hot sexy (parfum)', 'femmes', 0, 0, 5, '🌸'),
  (59, 'Roskstar old spice (parfum)', 'femmes', 0, 0, 5, '🌸'),
  (60, 'Volume & body (lait de corps)', 'femmes', 0, 0, 5, '🧴'),
  (61, 'Amalfi (color crème)', 'femmes', 0, 0, 5, '🧴'),
  (62, 'Jaclin hair mist (parfum)', 'femmes', 0, 0, 5, '🌸'),
  (63, 'Karatin salon level (hair mask)', 'femmes', 0, 0, 5, '🧖‍♀️'),
  (64, 'Schwarzkopf (pure color)', 'femmes', 0, 0, 5, '🎨'),
  (65, 'L''Oréal paris (coloration soin glossy)', 'femmes', 0, 0, 5, '🎨'),
  (66, 'Syoss zéro ammoniac (oil color)', 'femmes', 0, 0, 5, '🫙'),
  (67, 'Kativa karatina (lait de corps)', 'femmes', 0, 0, 5, '🧴'),
  (68, 'Byphasse avocat (gel de douche exfoliant)', 'femmes', 0, 0, 5, '💧'),
  (69, 'Sanitas (lime ongle électrique)', 'femmes', 0, 0, 5, '💅'),
  (70, 'Revlon colorsilk (pour cheveux)', 'femmes', 0, 0, 5, '💄'),
  (71, 'Diamond liss (spay lissant brillance vernis)', 'femmes', 0, 0, 5, '💅'),
  (72, 'Laser white (strengthening oil)', 'femmes', 0, 0, 5, '🫙'),
  (73, 'Venus (sérum anti frizz)', 'femmes', 0, 0, 5, '💧'),
  (74, 'Mixa (huile anti vergetures)', 'femmes', 0, 0, 5, '🫙'),
  (75, 'L''Oréal paris elseve soin magique (huil pour cheveux)', 'femmes', 0, 0, 5, '💄'),
  (76, 'Baslque (sérum total repair)', 'femmes', 0, 0, 5, '💧'),
  (77, 'Medix5.5 vitamine c+ (lait de corps)', 'femmes', 0, 0, 5, '🧴'),
  (78, 'Vaseline (petit pot)', 'femmes', 0, 0, 5, '🧴'),
  (79, 'Ikt wax stick (crème)', 'femmes', 0, 0, 5, '🧴'),
  (80, 'Nile (émall pour ongles)', 'femmes', 0, 0, 5, '💅'),
  (81, 'Japan flower (crème hydratante)', 'femmes', 0, 0, 5, '🧴'),
  (82, 'Saada baby (Vaseline)', 'femmes', 0, 0, 5, '🧴'),
  (83, 'Skin doctor Goat milk (lait de corps)', 'femmes', 0, 0, 5, '🧴'),
  (84, 'Cosmolive (pot haire mask)', 'femmes', 0, 0, 5, '🧖‍♀️'),
  (85, 'Argán hydratante (lait de corps)', 'femmes', 0, 0, 5, '🧴'),
  (86, 'Colgate max white charbon', 'femmes', 0, 0, 5, '🪥'),
  (87, 'Egl risky business (parfum)', 'femmes', 0, 0, 5, '🌸'),
  (88, 'Honey gel sleep mask', 'femmes', 0, 0, 5, '💧'),
  (89, 'Collagen booster (pot crème)', 'femmes', 0, 0, 5, '🧴'),
  (90, 'Secrat (parfum)', 'femmes', 0, 0, 5, '🌸'),
  (91, 'Vaseline blanche pot', 'femmes', 0, 0, 5, '🧴'),
  (92, 'Gants visage', 'femmes', 0, 0, 5, '🧤'),
  (93, 'Gants kisseu nile', 'femmes', 0, 0, 5, '🧤'),
  (94, 'Pierre pour pieds', 'femmes', 0, 0, 5, '🪨'),
  (95, 'Pantene Superalimento', 'femmes', 0, 0, 5, '🧴'),
  (96, 'Chaussettes', 'femmes', 0, 0, 5, '🧦'),
  (97, 'Rasoir femme', 'femmes', 0, 0, 5, '🪒'),
  (98, 'Ziala sachets (masque visage liquide)', 'femmes', 0, 0, 5, '🧖‍♀️'),
  (99, 'Gants simple', 'femmes', 0, 0, 5, '🧤'),
  (100, 'Brosse a dents', 'femmes', 0, 0, 5, '🪮'),
  (101, 'Brosse cheveux', 'femmes', 0, 0, 5, '🪮'),
  (102, 'Byphasse (huile de ricin fortifiant)', 'femmes', 0, 0, 5, '🫙'),
  (103, 'Papaya hair drink (huile)', 'femmes', 0, 0, 5, '🫙'),
  (104, 'Évoluderm keratine liquide', 'femmes', 0, 0, 5, '💄'),
  (105, 'Amalfi aloe vera (crème idratante)', 'femmes', 0, 0, 5, '🧴'),
  (106, 'Brosse cheveux fine', 'femmes', 0, 0, 5, '🪮'),
  (107, 'Labello Boom a levre', 'femmes', 0, 0, 5, '💄'),
  (108, 'Melano spotfree (crème visage)', 'femmes', 0, 0, 5, '🧴'),
  (109, 'Body lotion (crème corps)', 'femmes', 0, 0, 5, '🧴'),
  (110, 'Dax pomade pot', 'femmes', 0, 0, 5, '💄'),
  (111, 'Collagen pro 7.3 (hair color)', 'femmes', 0, 0, 5, '🎨'),
  (112, 'Bighai (lait parfum + masque)', 'femmes', 0, 0, 5, '🌸'),
  (113, 'Sk-hans (4 crème main)', 'femmes', 0, 0, 5, '🧴'),
  (114, 'Chouchou', 'femmes', 0, 0, 5, '🎀'),
  (115, 'Calliderme (crème main et ongles)', 'femmes', 0, 0, 5, '🧴'),
  (116, 'Beauty city BB crème', 'femmes', 0, 0, 5, '🧴'),
  (117, 'Argan (crème corps)', 'femmes', 0, 0, 5, '🧴'),
  (118, 'Bamboo charcoal (pour net)', 'femmes', 0, 0, 5, '💄'),
  (119, 'Crème déodorant', 'femmes', 0, 0, 5, '🧴'),
  (120, 'Magic clean (crème)', 'femmes', 0, 0, 5, '🧴'),
  (121, 'Net (crème pour le corps)', 'femmes', 0, 0, 5, '🧴'),
  (122, 'Captain (parfum)', 'femmes', 0, 0, 5, '🌸'),
  (123, 'Boîte crème pour enfant', 'femmes', 0, 0, 5, '🧴'),
  (124, 'Cosmolive micellar water (pour peau)', 'femmes', 0, 0, 5, '💧'),
  (125, 'Nature (savon triangle)', 'femmes', 0, 0, 5, '🧼'),
  (126, 'Mini ventilateur', 'femmes', 0, 0, 5, '🌀'),
  (127, 'Face fresh gold', 'femmes', 0, 0, 5, '💄'),
  (128, 'Épingle pour voile', 'femmes', 0, 0, 5, '📌'),
  (129, 'Pastil (sérum cheveux)', 'femmes', 0, 0, 5, '💧'),
  (130, 'Le chat (savons)', 'femmes', 0, 0, 5, '💄'),
  (131, 'Mustela (crème de corps)', 'femmes', 0, 0, 5, '🧴'),
  (132, 'Vitfé (crème pour os)', 'femmes', 0, 0, 5, '🧴'),
  (133, 'Sulfure8 kids (crème cheveux)', 'femmes', 0, 0, 5, '🧴'),
  (134, 'Calliderme gel intime', 'femmes', 0, 0, 5, '💧'),
  (135, 'Évoluderm après shampoo', 'femmes', 0, 0, 5, '🧴'),
  (136, 'Miss wendy (gel aloe vera)', 'femmes', 0, 0, 5, '💧'),
  (137, 'Hashmi (colle cil)', 'femmes', 0, 0, 5, '👁️'),
  (138, 'Dialabé', 'hommes', 0, 22, 4, '🧵'),
  (139, 'Sous-vêtements', 'hommes', 0, 17, 3, '🩲'),
  (140, 'T-shirt', 'hommes', 0, 1, 1, '👕'),
  (141, 'Pantalon fine', 'hommes', 0, 12, 2, '👖'),
  (142, 'Champoo', 'hommes', 0, 15, 3, '🧴'),
  (143, 'Gamme', 'hommes', 0, 2, 1, '🎁'),
  (144, 'L''Oréal men crème de peau', 'hommes', 0, 4, 1, '🧴'),
  (145, 'Poudre', 'hommes', 0, 4, 1, '🧴'),
  (146, 'Parfum 2K', 'hommes', 0, 14, 3, '🌸'),
  (147, 'Parfum Aroma', 'hommes', 0, 23, 5, '🌸'),
  (148, 'Gel nettoyant', 'hommes', 0, 3, 1, '💧'),
  (149, 'Herbal inhaler (menthe)', 'hommes', 0, 6, 1, '💨'),
  (150, 'Chaussettes (paire)', 'hommes', 0, 5, 1, '🧦'),
  (151, 'Parfum Jacklin', 'hommes', 0, 34, 7, '🌸'),
  (152, 'Vaseline (paquet)', 'hommes', 0, 1, 1, '🧴'),
  (153, 'Gamme Poseidon', 'hommes', 0, 1, 1, '🎁'),
  (154, 'Gamme Night Lure', 'hommes', 0, 1, 1, '🎁'),
  (155, 'Vaseline Sada', 'hommes', 0, 1, 1, '🧴'),
  (156, 'Mousse à raser', 'hommes', 0, 22, 4, '🪒'),
  (157, 'Baume après-rasage', 'hommes', 0, 22, 4, '🪒'),
  (158, 'Parfum Onlyou', 'hommes', 0, 6, 1, '🌸'),
  (159, 'Stick 5ml', 'hommes', 0, 13, 3, '🧴'),
  (160, 'Stick 3ml', 'hommes', 0, 2, 1, '🧴'),
  (161, 'Stick 2ml', 'hommes', 0, 5, 1, '🧴'),
  (162, 'Parfum AXE', 'hommes', 0, 7, 1, '🌸'),
  (163, 'Gamme visage', 'hommes', 0, 3, 1, '🎁'),
  (164, 'Champoo barbe', 'hommes', 0, 3, 1, '🧔'),
  (165, 'Savon à raser', 'hommes', 0, 2, 1, '🧼'),
  (166, 'Eau de Cologne barbe', 'hommes', 0, 1, 1, '🌸'),
  (167, 'Teinture cheveux (paquet)', 'hommes', 0, 1, 1, '🎨'),
  (168, 'Baume après-rasage 5ml', 'hommes', 0, 1, 1, '🪒'),
  (169, 'Pommade coco (pot)', 'hommes', 0, 1, 1, '🧴'),
  (170, 'Savon olive (pot)', 'hommes', 0, 1, 1, '🧼'),
  (171, 'Sachet karité 2cent', 'hommes', 0, 11, 2, '🧴'),
  (172, 'Chapelet', 'hommes', 0, 3, 1, '📿'),
  (173, 'Dove Men (bouteille)', 'hommes', 0, 2, 1, '🧴'),
  (174, 'Boubou Chigueu 10 mètres', 'hommes', 0, 4, 1, '🥻'),
  (175, 'Boubou Chigueu 8 mètres', 'hommes', 0, 4, 1, '🥻'),
  (176, 'Boubou Chigueu Saoudite', 'hommes', 0, 8, 2, '🥻'),
  (177, 'Boubou Joumani', 'hommes', 0, 12, 2, '🥻'),
  (178, 'Boubou Dollar', 'hommes', 0, 3, 1, '🥻'),
  (179, 'Baume après-rasage Brute', 'hommes', 0, 3, 1, '🪒'),
  (180, 'Longue chaîne', 'hommes', 0, 2, 1, '⛓️'),
  (181, 'Casquette', 'hommes', 0, 5, 1, '🧢'),
  (182, 'Trikko', 'hommes', 0, 3, 1, '🧥'),
  (183, 'Culotte enfant', 'hommes', 0, 11, 2, '🩲'),
  (184, 'Signal (dentifrice)', 'hommes', 0, 8, 2, '🪥'),
  (185, 'Briquets', 'hommes', 0, 1, 1, '🔥'),
  (186, 'Calpet', 'hommes', 0, 3, 1, '🧣'),
  (187, 'Bague', 'hommes', 0, 8, 2, '💍')
ON CONFLICT (id) DO NOTHING;
